import { Country } from '@/types'

export const COUNTRIES: Record<string, Country> = {
  TR: { name:'Türkiye',    flag:'🇹🇷', lang:'tr', intlLocale:'tr-TR', currency:'TRY', rate:1,      decimals:0 },
  CH: { name:'İsviçre',   flag:'🇨🇭', lang:'de', intlLocale:'de-CH', currency:'CHF', rate:1/42,   decimals:2 },
  DE: { name:'Almanya',   flag:'🇩🇪', lang:'de', intlLocale:'de-DE', currency:'EUR', rate:1/40,   decimals:2 },
  AT: { name:'Avusturya', flag:'🇦🇹', lang:'de', intlLocale:'de-AT', currency:'EUR', rate:1/40,   decimals:2 },
  IT: { name:'İtalya',    flag:'🇮🇹', lang:'it', intlLocale:'it-IT', currency:'EUR', rate:1/40,   decimals:2 },
  FR: { name:'Fransa',    flag:'🇫🇷', lang:'fr', intlLocale:'fr-FR', currency:'EUR', rate:1/40,   decimals:2 },
  BE: { name:'Belçika',   flag:'🇧🇪', lang:'fr', intlLocale:'fr-BE', currency:'EUR', rate:1/40,   decimals:2 },
  ES: { name:'İspanya',   flag:'🇪🇸', lang:'es', intlLocale:'es-ES', currency:'EUR', rate:1/40,   decimals:2 },
  PT: { name:'Portekiz',  flag:'🇵🇹', lang:'pt', intlLocale:'pt-PT', currency:'EUR', rate:1/40,   decimals:2 },
  NL: { name:'Hollanda',  flag:'🇳🇱', lang:'nl', intlLocale:'nl-NL', currency:'EUR', rate:1/40,   decimals:2 },
  DK: { name:'Danimarka', flag:'🇩🇰', lang:'da', intlLocale:'da-DK', currency:'DKK', rate:1/5.4,  decimals:0 },
  SE: { name:'İsveç',     flag:'🇸🇪', lang:'sv', intlLocale:'sv-SE', currency:'SEK', rate:1/3.5,  decimals:0 },
  FI: { name:'Finlandiya',flag:'🇫🇮', lang:'fi', intlLocale:'fi-FI', currency:'EUR', rate:1/40,   decimals:2 },
  NO: { name:'Norveç',    flag:'🇳🇴', lang:'no', intlLocale:'nb-NO', currency:'NOK', rate:1/3.5,  decimals:0 },
  US: { name:'USA',       flag:'🇺🇸', lang:'en', intlLocale:'en-US', currency:'USD', rate:1/36,   decimals:2 },
  GB: { name:'UK',        flag:'🇬🇧', lang:'en', intlLocale:'en-GB', currency:'GBP', rate:1/46,   decimals:2 },
  RU: { name:'Rusya',     flag:'🇷🇺', lang:'ru', intlLocale:'ru-RU', currency:'RUB', rate:2.7,    decimals:0 },
}

type LangKey = 'tr'|'en'|'de'|'fr'|'es'|'it'|'pt'|'nl'|'da'|'sv'|'fi'|'no'|'ru'

export type TranslationKey =
  | 'nav_discover' | 'nav_products' | 'nav_suppliers' | 'nav_analytics' | 'nav_login'
  | 'cart' | 'add_to_cart' | 'detail_btn' | 'checkout' | 'logout'
  | 'filter_all' | 'filter_mama' | 'filter_kum' | 'filter_tasma' | 'filter_oyuncak' | 'filter_kiyafet' | 'filter_yatak'
  | 'search_placeholder' | 'cart_empty' | 'cart_total' | 'reviews_label'
  | 'hero_eyebrow' | 'hero_h1' | 'hero_p' | 'btn_catalog' | 'btn_suppliers' | 'supplier_label'
  | 'color_label' | 'size_label' | 'qty_label'
  | 'co_title' | 'co_step1' | 'co_step2' | 'co_step3'
  | 'co_firstname' | 'co_lastname' | 'co_email' | 'co_phone'
  | 'co_address' | 'co_city' | 'co_zip' | 'co_country'
  | 'co_next' | 'co_back' | 'co_place_order'
  | 'co_std' | 'co_std_days' | 'co_exp' | 'co_exp_days'
  | 'co_subtotal' | 'co_shipping' | 'co_total' | 'co_free'
  | 'co_required' | 'co_order_summary'
  | 'co_success_title' | 'co_success_msg' | 'co_continue' | 'co_order_num'

export const TRANSLATIONS: Record<LangKey, Record<TranslationKey, string>> = {
  tr: { nav_discover:'Keşfet', nav_products:'Ürünler', nav_suppliers:'Tedarikçiler', nav_analytics:'Analiz', nav_login:'Giriş', cart:'Sepet', add_to_cart:'Sepete Ekle', detail_btn:'Detayları Gör', checkout:'Ödemeye Git', logout:'Çıkış', filter_all:'Hepsi', filter_mama:'Mama Kabı', filter_kum:'Kum Temizleyici', filter_tasma:'Tasma', filter_oyuncak:'Oyuncak', filter_kiyafet:'Kıyafet', filter_yatak:'Yatak', search_placeholder:'Ürün ara...', cart_empty:'Sepetinize ürün ekleyin.', cart_total:'Toplam:', reviews_label:'yorum', hero_eyebrow:'Çin kaynaklı — Dünyanın her yerine teslimat', hero_h1:'Tüylü dostuna en iyisini seç.', hero_p:'Akıllı mama kaplarından otomatik kum temizleyicilere, tasma setlerinden lüks yataklara — ISO sertifikalı Çin fabrikalarından kapına teslim.', btn_catalog:'Ürünleri Keşfet', btn_suppliers:'Tedarikçileri Gör', supplier_label:'Üretici Firma:', color_label:'Renk:', size_label:'Beden:', qty_label:'Adet:', co_title:'Sipariş Ver', co_step1:'Bilgileriniz', co_step2:'Teslimat Adresi', co_step3:'Kargo & Özet', co_firstname:'Ad', co_lastname:'Soyad', co_email:'E-posta', co_phone:'Telefon', co_address:'Adres', co_city:'Şehir / İl', co_zip:'Posta Kodu', co_country:'Ülke', co_next:'Devam Et', co_back:'Geri', co_place_order:'Siparişi Onayla', co_std:'Standart Kargo', co_std_days:'3–5 iş günü', co_exp:'Hızlı Kargo', co_exp_days:'1–2 iş günü', co_subtotal:'Ara Toplam', co_shipping:'Kargo', co_total:'Genel Toplam', co_free:'Ücretsiz', co_required:'Bu alan zorunludur', co_order_summary:'Sipariş Özeti', co_success_title:'Siparişiniz Alındı!', co_success_msg:'Teşekkürler! Sipariş onayı e-posta adresinize gönderildi.', co_continue:'Alışverişe Devam', co_order_num:'Sipariş No' },
  en: { nav_discover:'Discover', nav_products:'Products', nav_suppliers:'Suppliers', nav_analytics:'Analytics', nav_login:'Login', cart:'Cart', add_to_cart:'Add to Cart', detail_btn:'View Details', checkout:'Checkout', logout:'Logout', filter_all:'All', filter_mama:'Food Bowl', filter_kum:'Litter Cleaner', filter_tasma:'Leash', filter_oyuncak:'Toy', filter_kiyafet:'Clothing', filter_yatak:'Bed', search_placeholder:'Search products...', cart_empty:'Add products to your cart.', cart_total:'Total:', reviews_label:'reviews', hero_eyebrow:'Sourced from China — delivered worldwide', hero_h1:'Give your furry friend the best.', hero_p:'From smart food bowls to automatic litter cleaners, leash sets to luxury beds — ISO-certified products, delivered to your door.', btn_catalog:'Explore Products', btn_suppliers:'View Suppliers', supplier_label:'Manufacturer:', color_label:'Color:', size_label:'Size:', qty_label:'Qty:', co_title:'Place Order', co_step1:'Your Details', co_step2:'Shipping Address', co_step3:'Shipping & Summary', co_firstname:'First Name', co_lastname:'Last Name', co_email:'Email', co_phone:'Phone', co_address:'Address', co_city:'City', co_zip:'Postal Code', co_country:'Country', co_next:'Continue', co_back:'Back', co_place_order:'Place Order', co_std:'Standard Shipping', co_std_days:'7–14 business days', co_exp:'Express Shipping', co_exp_days:'3–5 business days', co_subtotal:'Subtotal', co_shipping:'Shipping', co_total:'Total', co_free:'Free', co_required:'This field is required', co_order_summary:'Order Summary', co_success_title:'Order Received!', co_success_msg:'Thank you! Order confirmation has been sent to your email.', co_continue:'Continue Shopping', co_order_num:'Order No' },
  de: { nav_discover:'Entdecken', nav_products:'Produkte', nav_suppliers:'Lieferanten', nav_analytics:'Analyse', nav_login:'Anmelden', cart:'Warenkorb', add_to_cart:'In den Warenkorb', detail_btn:'Details ansehen', checkout:'Zur Kasse', logout:'Abmelden', filter_all:'Alle', filter_mama:'Futternapf', filter_kum:'Katzentoilette', filter_tasma:'Leine', filter_oyuncak:'Spielzeug', filter_kiyafet:'Kleidung', filter_yatak:'Bett', search_placeholder:'Produkt suchen...', cart_empty:'Fügen Sie Produkte hinzu.', cart_total:'Gesamt:', reviews_label:'Bewertungen', hero_eyebrow:'Aus China — weltweiter Versand', hero_h1:'Das Beste für Ihren Vierbeiner.', hero_p:'Von Futterspendern bis zu Katzentoiletten, Leinensätze bis zu Luxusbetten — ISO-zertifiziert, direkt geliefert.', btn_catalog:'Produkte entdecken', btn_suppliers:'Lieferanten ansehen', supplier_label:'Hersteller:', color_label:'Farbe:', size_label:'Größe:', qty_label:'Menge:', co_title:'Bestellung aufgeben', co_step1:'Ihre Daten', co_step2:'Lieferadresse', co_step3:'Versand & Zusammenfassung', co_firstname:'Vorname', co_lastname:'Nachname', co_email:'E-Mail', co_phone:'Telefon', co_address:'Adresse', co_city:'Stadt', co_zip:'Postleitzahl', co_country:'Land', co_next:'Weiter', co_back:'Zurück', co_place_order:'Bestellung aufgeben', co_std:'Standardversand', co_std_days:'7–14 Werktage', co_exp:'Expressversand', co_exp_days:'3–5 Werktage', co_subtotal:'Zwischensumme', co_shipping:'Versand', co_total:'Gesamtsumme', co_free:'Kostenlos', co_required:'Pflichtfeld', co_order_summary:'Bestellübersicht', co_success_title:'Bestellung eingegangen!', co_success_msg:'Vielen Dank! Eine Bestellbestätigung wurde an Ihre E-Mail gesendet.', co_continue:'Weiter einkaufen', co_order_num:'Bestellnr.' },
  fr: { nav_discover:'Découvrir', nav_products:'Produits', nav_suppliers:'Fournisseurs', nav_analytics:'Analyses', nav_login:'Connexion', cart:'Panier', add_to_cart:'Ajouter au panier', detail_btn:'Voir les détails', checkout:'Commander', logout:'Déconnexion', filter_all:'Tout', filter_mama:'Gamelle', filter_kum:'Litière auto.', filter_tasma:'Laisse', filter_oyuncak:'Jouet', filter_kiyafet:'Vêtement', filter_yatak:'Lit', search_placeholder:'Rechercher...', cart_empty:'Ajoutez des produits.', cart_total:'Total:', reviews_label:'avis', hero_eyebrow:'Sourcé en Chine — livraison mondiale', hero_h1:'Offrez le meilleur à votre animal.', hero_p:"Des gamelles connectées aux litières automatiques — produits ISO certifiés livrés chez vous.", btn_catalog:'Explorer les produits', btn_suppliers:'Voir les fournisseurs', supplier_label:'Fournisseur:', color_label:'Couleur:', size_label:'Taille:', qty_label:'Qté:', co_title:'Passer commande', co_step1:'Vos coordonnées', co_step2:'Adresse de livraison', co_step3:'Livraison & Récapitulatif', co_firstname:'Prénom', co_lastname:'Nom', co_email:'E-mail', co_phone:'Téléphone', co_address:'Adresse', co_city:'Ville', co_zip:'Code postal', co_country:'Pays', co_next:'Continuer', co_back:'Retour', co_place_order:'Passer la commande', co_std:'Livraison standard', co_std_days:'7–14 jours ouvrés', co_exp:'Livraison express', co_exp_days:'3–5 jours ouvrés', co_subtotal:'Sous-total', co_shipping:'Livraison', co_total:'Total', co_free:'Gratuit', co_required:'Champ obligatoire', co_order_summary:'Récapitulatif', co_success_title:'Commande reçue !', co_success_msg:'Merci ! Une confirmation a été envoyée à votre e-mail.', co_continue:'Continuer les achats', co_order_num:'N° de commande' },
  es: { nav_discover:'Descubrir', nav_products:'Productos', nav_suppliers:'Proveedores', nav_analytics:'Análisis', nav_login:'Iniciar sesión', cart:'Carrito', add_to_cart:'Añadir al carrito', detail_btn:'Ver detalles', checkout:'Ir al pago', logout:'Cerrar sesión', filter_all:'Todos', filter_mama:'Comedero', filter_kum:'Limpiadora arena', filter_tasma:'Correa', filter_oyuncak:'Juguete', filter_kiyafet:'Ropa', filter_yatak:'Cama', search_placeholder:'Buscar...', cart_empty:'Añade productos al carrito.', cart_total:'Total:', reviews_label:'reseñas', hero_eyebrow:'De China — envío mundial', hero_h1:'Lo mejor para tu amigo peludo.', hero_p:'Comederos inteligentes, areneros automáticos, correas y camas de lujo — ISO certificados a tu puerta.', btn_catalog:'Explorar productos', btn_suppliers:'Ver proveedores', supplier_label:'Proveedor:', color_label:'Color:', size_label:'Talla:', qty_label:'Cant.:', co_title:'Realizar pedido', co_step1:'Tus datos', co_step2:'Dirección de envío', co_step3:'Envío & Resumen', co_firstname:'Nombre', co_lastname:'Apellido', co_email:'Correo', co_phone:'Teléfono', co_address:'Dirección', co_city:'Ciudad', co_zip:'Código postal', co_country:'País', co_next:'Continuar', co_back:'Atrás', co_place_order:'Confirmar pedido', co_std:'Envío estándar', co_std_days:'7–14 días hábiles', co_exp:'Envío exprés', co_exp_days:'3–5 días hábiles', co_subtotal:'Subtotal', co_shipping:'Envío', co_total:'Total', co_free:'Gratis', co_required:'Campo obligatorio', co_order_summary:'Resumen del pedido', co_success_title:'¡Pedido recibido!', co_success_msg:'¡Gracias! Se ha enviado una confirmación a tu correo.', co_continue:'Seguir comprando', co_order_num:'N.º de pedido' },
  it: { nav_discover:'Scopri', nav_products:'Prodotti', nav_suppliers:'Fornitori', nav_analytics:'Analisi', nav_login:'Accedi', cart:'Carrello', add_to_cart:'Aggiungi al carrello', detail_btn:'Vedi dettagli', checkout:'Procedi', logout:'Esci', filter_all:'Tutti', filter_mama:'Ciotola', filter_kum:'Lettiera auto.', filter_tasma:'Guinzaglio', filter_oyuncak:'Giocattolo', filter_kiyafet:'Abbigliamento', filter_yatak:'Cuccia', search_placeholder:'Cerca prodotti...', cart_empty:'Aggiungi prodotti.', cart_total:'Totale:', reviews_label:'recensioni', hero_eyebrow:'Dalla Cina — spedizione mondiale', hero_h1:'Il meglio per il tuo amico peloso.', hero_p:'Distributori automatici, lettiere robotiche e cucce di lusso — ISO certificati, consegnati a casa.', btn_catalog:'Scopri i prodotti', btn_suppliers:'Vedi fornitori', supplier_label:'Fornitore:', color_label:'Colore:', size_label:'Taglia:', qty_label:'Qtà:', co_title:'Effettua ordine', co_step1:'I tuoi dati', co_step2:'Indirizzo di spedizione', co_step3:'Spedizione & Riepilogo', co_firstname:'Nome', co_lastname:'Cognome', co_email:'E-mail', co_phone:'Telefono', co_address:'Indirizzo', co_city:'Città', co_zip:'CAP', co_country:'Paese', co_next:'Continua', co_back:'Indietro', co_place_order:'Conferma ordine', co_std:'Spedizione standard', co_std_days:'7–14 giorni lavorativi', co_exp:'Spedizione express', co_exp_days:'3–5 giorni lavorativi', co_subtotal:'Subtotale', co_shipping:'Spedizione', co_total:'Totale', co_free:'Gratuita', co_required:'Campo obbligatorio', co_order_summary:"Riepilogo ordine", co_success_title:'Ordine ricevuto!', co_success_msg:'Grazie! Una conferma è stata inviata alla tua e-mail.', co_continue:'Continua gli acquisti', co_order_num:'N. ordine' },
  pt: { nav_discover:'Descobrir', nav_products:'Produtos', nav_suppliers:'Fornecedores', nav_analytics:'Análise', nav_login:'Entrar', cart:'Carrinho', add_to_cart:'Adicionar', detail_btn:'Ver detalhes', checkout:'Finalizar', logout:'Sair', filter_all:'Todos', filter_mama:'Comedouro', filter_kum:'Limpadora', filter_tasma:'Coleira', filter_oyuncak:'Brinquedo', filter_kiyafet:'Roupa', filter_yatak:'Cama', search_placeholder:'Pesquisar...', cart_empty:'Adicione produtos.', cart_total:'Total:', reviews_label:'avaliações', hero_eyebrow:'Da China — entrega mundial', hero_h1:'O melhor para o seu animal.', hero_p:'Comedouros inteligentes, caixas automáticas e camas de luxo — certificados ISO, entregues em casa.', btn_catalog:'Explorar produtos', btn_suppliers:'Ver fornecedores', supplier_label:'Fornecedor:', color_label:'Cor:', size_label:'Tamanho:', qty_label:'Qtd.:', co_title:'Fazer pedido', co_step1:'Seus dados', co_step2:'Endereço de entrega', co_step3:'Frete & Resumo', co_firstname:'Nome', co_lastname:'Sobrenome', co_email:'E-mail', co_phone:'Telefone', co_address:'Endereço', co_city:'Cidade', co_zip:'CEP', co_country:'País', co_next:'Continuar', co_back:'Voltar', co_place_order:'Confirmar pedido', co_std:'Frete padrão', co_std_days:'7–14 dias úteis', co_exp:'Frete expresso', co_exp_days:'3–5 dias úteis', co_subtotal:'Subtotal', co_shipping:'Frete', co_total:'Total', co_free:'Grátis', co_required:'Campo obrigatório', co_order_summary:'Resumo do pedido', co_success_title:'Pedido recebido!', co_success_msg:'Obrigado! Uma confirmação foi enviada para o seu e-mail.', co_continue:'Continuar comprando', co_order_num:'N.º do pedido' },
  nl: { nav_discover:'Ontdekken', nav_products:'Producten', nav_suppliers:'Leveranciers', nav_analytics:'Analyse', nav_login:'Inloggen', cart:'Winkelwagen', add_to_cart:'In winkelwagen', detail_btn:'Details bekijken', checkout:'Afrekenen', logout:'Uitloggen', filter_all:'Alle', filter_mama:'Voerbak', filter_kum:'Kattenbak', filter_tasma:'Riem', filter_oyuncak:'Speelgoed', filter_kiyafet:'Kleding', filter_yatak:'Bed', search_placeholder:'Zoeken...', cart_empty:'Voeg producten toe.', cart_total:'Totaal:', reviews_label:'reviews', hero_eyebrow:'Uit China — wereldwijde levering', hero_h1:'Het beste voor uw huisdier.', hero_p:'Van slimme voerbakken tot kattenbakken, halsbandensets tot luxe bedden — ISO-gecertificeerd geleverd.', btn_catalog:'Ontdekken', btn_suppliers:'Leveranciers', supplier_label:'Leverancier:', color_label:'Kleur:', size_label:'Maat:', qty_label:'Aantal:', co_title:'Bestelling plaatsen', co_step1:'Uw gegevens', co_step2:'Bezorgadres', co_step3:'Verzending & Overzicht', co_firstname:'Voornaam', co_lastname:'Achternaam', co_email:'E-mail', co_phone:'Telefoon', co_address:'Adres', co_city:'Stad', co_zip:'Postcode', co_country:'Land', co_next:'Doorgaan', co_back:'Terug', co_place_order:'Bestelling bevestigen', co_std:'Standaard verzending', co_std_days:'7–14 werkdagen', co_exp:'Expresverzending', co_exp_days:'3–5 werkdagen', co_subtotal:'Subtotaal', co_shipping:'Verzending', co_total:'Totaal', co_free:'Gratis', co_required:'Verplicht veld', co_order_summary:'Besteloverzicht', co_success_title:'Bestelling ontvangen!', co_success_msg:'Dank u! Een bevestiging is verzonden naar uw e-mail.', co_continue:'Verder winkelen', co_order_num:'Bestelnr.' },
  da: { nav_discover:'Opdag', nav_products:'Produkter', nav_suppliers:'Leverandører', nav_analytics:'Analyse', nav_login:'Log ind', cart:'Kurv', add_to_cart:'Læg i kurv', detail_btn:'Se detaljer', checkout:'Betal', logout:'Log ud', filter_all:'Alle', filter_mama:'Madskål', filter_kum:'Katteboks', filter_tasma:'Snor', filter_oyuncak:'Legetøj', filter_kiyafet:'Tøj', filter_yatak:'Seng', search_placeholder:'Søg...', cart_empty:'Tilføj produkter.', cart_total:'I alt:', reviews_label:'anmeldelser', hero_eyebrow:'Fra Kina — levering verden over', hero_h1:'Det bedste til din ven.', hero_p:'Smarte foderskåle, automatiske kattebakker og luksussenge — ISO-certificeret leveret.', btn_catalog:'Udforsk', btn_suppliers:'Leverandører', supplier_label:'Leverandør:', color_label:'Farve:', size_label:'Størrelse:', qty_label:'Antal:', co_title:'Afgiv ordre', co_step1:'Dine oplysninger', co_step2:'Leveringsadresse', co_step3:'Fragt & Oversigt', co_firstname:'Fornavn', co_lastname:'Efternavn', co_email:'E-mail', co_phone:'Telefon', co_address:'Adresse', co_city:'By', co_zip:'Postnummer', co_country:'Land', co_next:'Fortsæt', co_back:'Tilbage', co_place_order:'Bekræft ordre', co_std:'Standard fragt', co_std_days:'7–14 hverdage', co_exp:'Ekspres fragt', co_exp_days:'3–5 hverdage', co_subtotal:'Subtotal', co_shipping:'Fragt', co_total:'Total', co_free:'Gratis', co_required:'Påkrævet felt', co_order_summary:'Ordreoversigt', co_success_title:'Ordre modtaget!', co_success_msg:'Tak! En ordrebekræftelse er sendt til din e-mail.', co_continue:'Fortsæt shopping', co_order_num:'Ordrenr.' },
  sv: { nav_discover:'Upptäck', nav_products:'Produkter', nav_suppliers:'Leverantörer', nav_analytics:'Analys', nav_login:'Logga in', cart:'Varukorg', add_to_cart:'Lägg i varukorg', detail_btn:'Se detaljer', checkout:'Kassan', logout:'Logga ut', filter_all:'Alla', filter_mama:'Matskål', filter_kum:'Kattlåda', filter_tasma:'Koppel', filter_oyuncak:'Leksak', filter_kiyafet:'Kläder', filter_yatak:'Säng', search_placeholder:'Sök...', cart_empty:'Lägg till produkter.', cart_total:'Totalt:', reviews_label:'recensioner', hero_eyebrow:'Från Kina — leverans världen över', hero_h1:'Det bästa för din vän.', hero_p:'Smarta matautomater, kattlådor och lyxiga sängar — ISO-certifierade levererade hem.', btn_catalog:'Utforska', btn_suppliers:'Leverantörer', supplier_label:'Leverantör:', color_label:'Färg:', size_label:'Storlek:', qty_label:'Antal:', co_title:'Lägg beställning', co_step1:'Dina uppgifter', co_step2:'Leveransadress', co_step3:'Frakt & Sammanfattning', co_firstname:'Förnamn', co_lastname:'Efternamn', co_email:'E-post', co_phone:'Telefon', co_address:'Adress', co_city:'Stad', co_zip:'Postnummer', co_country:'Land', co_next:'Fortsätt', co_back:'Tillbaka', co_place_order:'Bekräfta beställning', co_std:'Standardfrakt', co_std_days:'7–14 vardagar', co_exp:'Expressfrakt', co_exp_days:'3–5 vardagar', co_subtotal:'Delsumma', co_shipping:'Frakt', co_total:'Totalt', co_free:'Gratis', co_required:'Obligatoriskt fält', co_order_summary:'Orderöversikt', co_success_title:'Beställning mottagen!', co_success_msg:'Tack! En orderbekräftelse har skickats till din e-post.', co_continue:'Fortsätt handla', co_order_num:'Ordernr.' },
  fi: { nav_discover:'Tutustu', nav_products:'Tuotteet', nav_suppliers:'Toimittajat', nav_analytics:'Analytiikka', nav_login:'Kirjaudu', cart:'Ostoskori', add_to_cart:'Lisää koriin', detail_btn:'Näytä tiedot', checkout:'Kassalle', logout:'Kirjaudu ulos', filter_all:'Kaikki', filter_mama:'Ruokakulho', filter_kum:'Hiekkalaatikko', filter_tasma:'Hihna', filter_oyuncak:'Lelu', filter_kiyafet:'Vaatteet', filter_yatak:'Peti', search_placeholder:'Hae tuotteita...', cart_empty:'Lisää tuotteita.', cart_total:'Yhteensä:', reviews_label:'arvostelua', hero_eyebrow:'Kiinasta — toimitus kaikkialle', hero_h1:'Parasta lemmikillesi.', hero_p:'Älykkäitä ruokinta-automaatteja, hiekkalaatikoita ja ylellisiä petiä — ISO-sertifioituja.', btn_catalog:'Tutustu tuotteisiin', btn_suppliers:'Toimittajat', supplier_label:'Toimittaja:', color_label:'Väri:', size_label:'Koko:', qty_label:'Määrä:', co_title:'Tee tilaus', co_step1:'Tietosi', co_step2:'Toimitusosoite', co_step3:'Toimitus & Yhteenveto', co_firstname:'Etunimi', co_lastname:'Sukunimi', co_email:'Sähköposti', co_phone:'Puhelin', co_address:'Osoite', co_city:'Kaupunki', co_zip:'Postinumero', co_country:'Maa', co_next:'Jatka', co_back:'Takaisin', co_place_order:'Vahvista tilaus', co_std:'Vakiotoimitus', co_std_days:'7–14 arkipäivää', co_exp:'Pikatoimitus', co_exp_days:'3–5 arkipäivää', co_subtotal:'Välisumma', co_shipping:'Toimitus', co_total:'Yhteensä', co_free:'Ilmainen', co_required:'Pakollinen kenttä', co_order_summary:'Tilausyhteenveto', co_success_title:'Tilaus vastaanotettu!', co_success_msg:'Kiitos! Tilausvahvistus on lähetetty sähköpostiisi.', co_continue:'Jatka ostoksia', co_order_num:'Tilausnro' },
  no: { nav_discover:'Oppdag', nav_products:'Produkter', nav_suppliers:'Leverandører', nav_analytics:'Analyse', nav_login:'Logg inn', cart:'Handlekurv', add_to_cart:'Legg i kurv', detail_btn:'Se detaljer', checkout:'Betal', logout:'Logg ut', filter_all:'Alle', filter_mama:'Matskål', filter_kum:'Katteboks', filter_tasma:'Bånd', filter_oyuncak:'Leketøy', filter_kiyafet:'Klær', filter_yatak:'Seng', search_placeholder:'Søk...', cart_empty:'Legg til produkter.', cart_total:'Totalt:', reviews_label:'anmeldelser', hero_eyebrow:'Fra Kina — levering til hele verden', hero_h1:'Det beste for din venn.', hero_p:'Smarte matskåler, kattebakker og luksussenger — ISO-sertifisert levert.', btn_catalog:'Utforsk', btn_suppliers:'Leverandører', supplier_label:'Leverandør:', color_label:'Farge:', size_label:'Størrelse:', qty_label:'Antall:', co_title:'Legg inn bestilling', co_step1:'Dine opplysninger', co_step2:'Leveringsadresse', co_step3:'Frakt & Oversikt', co_firstname:'Fornavn', co_lastname:'Etternavn', co_email:'E-post', co_phone:'Telefon', co_address:'Adresse', co_city:'By', co_zip:'Postnummer', co_country:'Land', co_next:'Fortsett', co_back:'Tilbake', co_place_order:'Bekreft bestilling', co_std:'Standard frakt', co_std_days:'7–14 virkedager', co_exp:'Ekspressfrakt', co_exp_days:'3–5 virkedager', co_subtotal:'Delsum', co_shipping:'Frakt', co_total:'Totalt', co_free:'Gratis', co_required:'Obligatorisk felt', co_order_summary:'Bestillingsoversikt', co_success_title:'Bestilling mottatt!', co_success_msg:'Takk! En bekreftelse er sendt til din e-post.', co_continue:'Fortsett å handle', co_order_num:'Bestillingsnr.' },
  ru: { nav_discover:'Обзор', nav_products:'Товары', nav_suppliers:'Поставщики', nav_analytics:'Аналитика', nav_login:'Войти', cart:'Корзина', add_to_cart:'В корзину', detail_btn:'Подробнее', checkout:'Оформить заказ', logout:'Выйти', filter_all:'Все', filter_mama:'Миска', filter_kum:'Туалет авто.', filter_tasma:'Поводок', filter_oyuncak:'Игрушка', filter_kiyafet:'Одежда', filter_yatak:'Лежанка', search_placeholder:'Поиск...', cart_empty:'Добавьте товары в корзину.', cart_total:'Итого:', reviews_label:'отзывов', hero_eyebrow:'Из Китая — доставка по всему миру', hero_h1:'Лучшее для вашего питомца.', hero_p:'Умные кормушки, автоматические туалеты, поводки и роскошные лежанки — ISO-сертифицированные товары.', btn_catalog:'Смотреть товары', btn_suppliers:'Поставщики', supplier_label:'Поставщик:', color_label:'Цвет:', size_label:'Размер:', qty_label:'Кол-во:', co_title:'Оформить заказ', co_step1:'Ваши данные', co_step2:'Адрес доставки', co_step3:'Доставка & Итог', co_firstname:'Имя', co_lastname:'Фамилия', co_email:'E-mail', co_phone:'Телефон', co_address:'Адрес', co_city:'Город', co_zip:'Индекс', co_country:'Страна', co_next:'Продолжить', co_back:'Назад', co_place_order:'Подтвердить заказ', co_std:'Стандартная доставка', co_std_days:'7–14 рабочих дней', co_exp:'Экспресс-доставка', co_exp_days:'3–5 рабочих дней', co_subtotal:'Подытог', co_shipping:'Доставка', co_total:'Итого', co_free:'Бесплатно', co_required:'Обязательное поле', co_order_summary:'Состав заказа', co_success_title:'Заказ принят!', co_success_msg:'Спасибо! Подтверждение отправлено на вашу почту.', co_continue:'Продолжить покупки', co_order_num:'№ заказа' },
}

export function getCountryConfig(code: string): Country {
  return COUNTRIES[code] ?? COUNTRIES.TR
}

export function getLang(code: string) {
  return getCountryConfig(code).lang as LangKey
}

export function t(countryCode: string, key: TranslationKey): string {
  const lang = getLang(countryCode)
  return TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.en[key] ?? key
}

export function formatPrice(tryAmount: number, countryCode: string): string {
  const cfg = getCountryConfig(countryCode)
  const amount = tryAmount * cfg.rate
  try {
    return new Intl.NumberFormat(cfg.intlLocale, {
      style: 'currency',
      currency: cfg.currency,
      minimumFractionDigits: cfg.decimals,
      maximumFractionDigits: cfg.decimals,
    }).format(amount)
  } catch {
    return amount.toFixed(cfg.decimals)
  }
}
