import { Product } from '@/types'

export const PRODUCTS: Product[] = [
  {
    id: 'autofeed-pro',
    name: 'AutoFeed Pro X1',
    category: 'mama-kabi',
    categoryLabel: 'Akıllı Mama Kabı',
    price: 1299,
    rating: 4.9,
    reviewCount: 284,
    badge: 'Çok Satan',
    images: [
      'https://images.unsplash.com/photo-1601758003122-53c40e686a19?w=700&h=520&fit=crop&auto=format&q=80',
      'https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=700&h=520&fit=crop&auto=format&q=80',
    ],
    thumbImage: 'https://images.unsplash.com/photo-1601758003122-53c40e686a19?w=600&h=420&fit=crop&auto=format&q=80',
    shortDesc: 'WiFi kontrollü, 5L hazne, günde 6 öğün programı.',
    description: 'AutoFeed Pro X1, mobil uygulamanız üzerinden tam kontrol sağlayan akıllı mama kabıdır. 5 litrelik büyük hazne ile uzun seyahatlerinizde bile dostunuzu aç bırakmaz. Günde 6 programlanabilir öğün ile düzenli beslenme alışkanlığı kazandırır.',
    features: ['iOS & Android uygulama kontrolü', '5L büyük hazne kapasitesi', 'Günde 6 öğün programlama', 'Düşük stok uyarısı bildirimi', 'BPA içermeyen gıda güvenli malzeme', 'Mama vakti ses kaydı (10 sn)'],
    colors: ['Beyaz', 'Siyah', 'Bej'],
    supplier: 'Guangzhou, Çin — Doğrudan Üretici',
    supplierNote: 'ISO 9001 & CE sertifikalı. 2 yıl garanti. Aracısız, fabrikadan direkt.',
  },
  {
    id: 'smartbowl-duo',
    name: 'SmartBowl Duo',
    category: 'mama-kabi',
    categoryLabel: 'Akıllı Mama Kabı',
    price: 799,
    rating: 4.7,
    reviewCount: 156,
    badge: 'En İyi Değer',
    images: [
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=700&h=520&fit=crop&auto=format&q=80',
      'https://images.unsplash.com/photo-1552053831-71594a27632d?w=700&h=520&fit=crop&auto=format&q=80',
    ],
    thumbImage: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=420&fit=crop&auto=format&q=80',
    shortDesc: 'Çift hazneli (mama + su), 4 öğün zamanlayıcı.',
    description: 'SmartBowl Duo hem mama hem de su haznesini tek ünitede birleştirir. Günde 4 programlanabilir öğün ile dostunuzun beslenmesini düzenler. Paslanmaz çelik kase ve çift güç kaynağı ile güvenilir kullanım sağlar.',
    features: ['Çift hazne: mama + 1.2L su', 'Günde 4 öğün zamanlayıcı', 'Paslanmaz çelik kase', 'Pil + adaptör çift güç', 'Dishwasher safe parçalar'],
    colors: ['Beyaz', 'Pembe', 'Mavi'],
    supplier: 'Guangzhou, Çin — Doğrudan Üretici',
    supplierNote: 'ISO 9001 sertifikalı. 1 yıl garanti. Aracısız, fabrikadan direkt.',
  },
  {
    id: 'cleanbot-pro',
    name: 'CleanBot Litter Pro',
    category: 'kum-temizleyici',
    categoryLabel: 'Otomatik Kum Temizleyici',
    price: 2899,
    rating: 4.8,
    reviewCount: 198,
    badge: 'Premium',
    images: [
      'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=700&h=520&fit=crop&auto=format&q=80',
      'https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=700&h=520&fit=crop&auto=format&q=80',
    ],
    thumbImage: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&h=420&fit=crop&auto=format&q=80',
    shortDesc: 'Sessiz motor (<35 dB), çift karbon filtre, uygulama kontrolü.',
    description: 'CleanBot Litter Pro, aktivite sensörü ile kediniz çıktıktan 10 dakika sonra otomatik temizlik yapar. Gürültüsüz motor teknolojisi kedilerin alışmasını kolaylaştırır. Çift katman karbon filtre kokuyu %99 azaltır.',
    features: ['Aktivite sensörü — 10 dk sonra oto temizlik', 'Gürültü < 35 dB', 'Çift katman karbon filtre', '7 günlük kullanım raporu', 'Büyük kapasiteli atık çekmecesi', 'Uygulama ile manuel kontrol'],
    colors: ['Beyaz', 'Siyah'],
    supplier: 'Shenzhen, Çin — Doğrudan Üretici',
    supplierNote: 'RoHS & CE sertifikalı. 2 yıl garanti. Aracısız, fabrikadan direkt.',
  },
  {
    id: 'scoopmate-classic',
    name: 'ScoopMate Classic',
    category: 'kum-temizleyici',
    categoryLabel: 'Otomatik Kum Temizleyici',
    price: 1199,
    rating: 4.5,
    reviewCount: 112,
    badge: 'Bütçe Dostu',
    images: [
      'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=700&h=520&fit=crop&auto=format&q=80',
      'https://images.unsplash.com/photo-1561948955-570b270e7c36?w=700&h=520&fit=crop&auto=format&q=80',
    ],
    thumbImage: 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=600&h=420&fit=crop&auto=format&q=80',
    shortDesc: 'Yarı otomatik, infrared sensörlü, karbon filtreli.',
    description: 'ScoopMate Classic başlangıç seviyesi için ideal fiyat-performans çözümüdür. Infrared sensör ile kedi ayrıldıktan 5 dakika sonra otomatik tırmıklama yapar. Basit ve sağlam mekanizması ile uzun yıllar sorunsuz çalışır.',
    features: ['Infrared hareket sensörü', 'Kedi çıkışından 5 dk sonra tırmıklama', 'Karbon filtre (koku giderici)', 'Kolay temizlenebilir tepsi', 'Aşırı yük koruması'],
    colors: ['Bej', 'Gri'],
    supplier: 'Shenzhen, Çin — Doğrudan Üretici',
    supplierNote: 'CE sertifikalı. 1 yıl garanti. Aracısız, fabrikadan direkt.',
  },
  {
    id: 'flexiwalk-set',
    name: 'FlexiWalk Tasma Set',
    category: 'tasma',
    categoryLabel: 'Tasma & Göğüs Kemeri',
    price: 289,
    rating: 4.7,
    reviewCount: 341,
    images: [
      'https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=700&h=520&fit=crop&auto=format&q=80',
      'https://images.unsplash.com/photo-1552053831-71594a27632d?w=700&h=520&fit=crop&auto=format&q=80',
    ],
    thumbImage: 'https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=600&h=420&fit=crop&auto=format&q=80',
    shortDesc: 'Neoprene astar, reflektif şerit, 5 renk 5 beden.',
    description: 'FlexiWalk Tasma Set kedi ve köpeklerin yürüyüş deneyimini en üst seviyeye taşır. Neoprene iç astar sürtünmeyi önler, reflektif şeritler gece güvenliğini sağlar.',
    features: ['Neoprene iç astar', 'Gece reflektif şerit', 'Hızlı bırakma alüminyum toka', 'Ayarlanabilir göğüs kemeri dahil', 'Yıkama makinasında yıkanabilir'],
    colors: ['Kırmızı', 'Mavi', 'Yeşil', 'Pembe', 'Siyah'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    supplier: 'Yiwu, Çin — Doğrudan Üretici',
    supplierNote: 'EN71 sertifikalı. Aracısız, fabrikadan direkt. 10+ adet siparişte %15 indirim.',
  },
  {
    id: 'easywalk-kosum',
    name: 'EasyWalk Koşum Takımı',
    category: 'tasma',
    categoryLabel: 'Anti-Çekiş Koşum',
    price: 219,
    rating: 4.6,
    reviewCount: 207,
    badge: 'Yeni',
    images: [
      'https://images.unsplash.com/photo-1552053831-71594a27632d?w=700&h=520&fit=crop&auto=format&q=80',
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=700&h=520&fit=crop&auto=format&q=80',
    ],
    thumbImage: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=600&h=420&fit=crop&auto=format&q=80',
    shortDesc: 'Anti-çekiş ön bağlantı, mesh kumaş, ergonomik.',
    description: 'EasyWalk Koşum Takımı çekme problemi yaşayan köpekler için geliştirilmiştir. Göğüs ön kısmındaki bağlantı noktası köpeği çekme davranışından doğal olarak caydırır.',
    features: ['Anti-çekiş ön bağlantı noktası', 'Nefes alan mesh kumaş', 'Kolay giyip çıkarma klipsi', 'Yan metal halka (standart)', 'S–XL ırk uyumlu'],
    colors: ['Gri', 'Turuncu', 'Lacivert'],
    sizes: ['S', 'M', 'L', 'XL'],
    supplier: 'Yiwu, Çin — Doğrudan Üretici',
    supplierNote: 'EN71 sertifikalı. 3–5 iş günü. Aracısız, fabrikadan direkt.',
  },
  {
    id: 'pacaveli-set',
    name: 'PaçaVeli Oyuncak Seti',
    category: 'oyuncak',
    categoryLabel: 'Oyuncak Seti — 12 Parça',
    price: 179,
    rating: 4.8,
    reviewCount: 512,
    badge: 'Çok Satan',
    images: [
      'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=700&h=520&fit=crop&auto=format&q=80',
      'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=700&h=520&fit=crop&auto=format&q=80',
    ],
    thumbImage: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&h=420&fit=crop&auto=format&q=80',
    shortDesc: 'Catnip fareler, lazer, tüy çubuğu, 12 parça.',
    description: 'PaçaVeli 12 parçalık kapsamlı oyuncak setidir. Doğal catnip fareler, lazer işaretçi, teleskopik tüy çubuğu ve çıngıraklı topları içerir.',
    features: ['12 parça çeşitli set', 'Doğal catnip özlü 3 fare', 'Otomatik lazer işaretçi', 'Teleskopik tüy çubuğu (70 cm)', '4 renkli çıngıraklı top', 'EN71 & zehirsiz malzeme'],
    supplier: 'Guangzhou, Çin — Doğrudan Üretici',
    supplierNote: 'EN71 sertifikalı. Hazır stok, hızlı sevkiyat. Aracısız, fabrikadan direkt.',
  },
  {
    id: 'laserbot-interactive',
    name: 'LaserBot Interaktif',
    category: 'oyuncak',
    categoryLabel: 'Otomatik Lazer Oyuncak',
    price: 349,
    rating: 4.7,
    reviewCount: 189,
    badge: 'Yeni',
    images: [
      'https://images.unsplash.com/photo-1561948955-570b270e7c36?w=700&h=520&fit=crop&auto=format&q=80',
      'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=700&h=520&fit=crop&auto=format&q=80',
    ],
    thumbImage: 'https://images.unsplash.com/photo-1561948955-570b270e7c36?w=600&h=420&fit=crop&auto=format&q=80',
    shortDesc: '360° otomatik lazer, 3 hız modu, 15 dk kapanma.',
    description: 'LaserBot Interaktif evde yokken de kedinizin aktif kalmasını sağlar. 360° dönen kafa tahmin edilemez lazer hareketleri üretir.',
    features: ['360° döner lazer kafası', '3 hız modu (Yavaş/Orta/Hızlı)', '15 dk sonra otomatik kapanma', 'USB şarj (pil dahil)', 'Sessiz motor', 'Kaymaz taban'],
    colors: ['Beyaz', 'Siyah'],
    supplier: 'Guangzhou, Çin — Doğrudan Üretici',
    supplierNote: 'CE sertifikalı. 6 ay garanti. Aracısız, fabrikadan direkt.',
  },
  {
    id: 'furstyle-sezon',
    name: 'FurStyle Sezon Kıyafeti',
    category: 'kiyafet',
    categoryLabel: 'Kıyafet — Kedi & Köpek',
    price: 319,
    rating: 4.6,
    reviewCount: 278,
    images: [
      'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=700&h=520&fit=crop&auto=format&q=80',
      'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=700&h=520&fit=crop&auto=format&q=80',
    ],
    thumbImage: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&h=420&fit=crop&auto=format&q=80',
    shortDesc: '%100 organik pamuk, 15+ desen, makine yıkama.',
    description: 'FurStyle Sezon Kıyafeti OEKO-TEX sertifikalı organik pamuk ile cilt tahriş etmez. Elastik bel bandı ve kolay çıkarma tasarımı ile giydirmek artık stres değil.',
    features: ['%100 organik pamuk (OEKO-TEX)', 'Elastik bel & kol bandı', '15+ desen seçeneği', 'Makine yıkama (30°C)', 'Kedi & köpek uyumlu'],
    colors: ['Çizgili', 'Puantiyeli', 'Düz Renk'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    supplier: 'Hangzhou, Çin — Doğrudan Üretici',
    supplierNote: 'OEKO-TEX sertifikalı kumaş. Sezonluk koleksiyon. Aracısız, fabrikadan direkt.',
  },
  {
    id: 'warmpaw-mont',
    name: 'WarmPaw Kış Montu',
    category: 'kiyafet',
    categoryLabel: 'Kış Montu — Kedi & Köpek',
    price: 449,
    rating: 4.8,
    reviewCount: 143,
    badge: 'Yeni Sezon',
    images: [
      'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=700&h=520&fit=crop&auto=format&q=80',
      'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=700&h=520&fit=crop&auto=format&q=80',
    ],
    thumbImage: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=600&h=420&fit=crop&auto=format&q=80',
    shortDesc: 'Su geçirmez dış yüzey, polar iç astar, reflektif.',
    description: 'WarmPaw Kış Montu soğuk ve yağışlı havalarda evcil hayvanınızı sıcak ve kuru tutar. Reflektif şeritleri alacakaranlık yürüyüşlerini güvenli kılar.',
    features: ['Su geçirmez ripstop dış kumaş', 'Yumuşak polar iç astar', 'Reflektif güvenlik şeridi', 'Tasma bağlantı deliği', 'Kolay giyip çıkarma', '5 renk seçeneği'],
    colors: ['Kırmızı', 'Lacivert', 'Yeşil', 'Siyah', 'Sarı'],
    sizes: ['S', 'M', 'L', 'XL'],
    supplier: 'Hangzhou, Çin — Doğrudan Üretici',
    supplierNote: 'OEKO-TEX sertifikalı. Aracısız, fabrikadan direkt.',
  },
  {
    id: 'cloudnap-lux',
    name: 'CloudNap Lüks Yatak',
    category: 'yatak',
    categoryLabel: 'Lüks Evcil Yatak',
    price: 749,
    rating: 4.9,
    reviewCount: 367,
    badge: 'Çok Satan',
    images: [
      'https://images.unsplash.com/photo-1503256207526-0d5523f39e50?w=700&h=520&fit=crop&auto=format&q=80',
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=700&h=520&fit=crop&auto=format&q=80',
    ],
    thumbImage: 'https://images.unsplash.com/photo-1503256207526-0d5523f39e50?w=600&h=420&fit=crop&auto=format&q=80',
    shortDesc: '5 cm memory foam, çıkarılabilir kılıf, kaymaz taban.',
    description: 'CloudNap Lüks Yatak CertiPUR-US sertifikalı 5 cm kalın memory foam tabanı ile ortopedik destek sağlar. Yaşlı veya eklem problemi yaşayan hayvanlarda ağrı azaltıcı etki gösterir.',
    features: ['5 cm CertiPUR-US memory foam', 'Çıkarılabilir kadife kılıf', 'Kaymaz silikon taban', 'Ortopedik baskı dağıtımı', 'S/M/L/XL boyut seçeneği'],
    colors: ['Gri', 'Bej', 'Koyu Kahve'],
    sizes: ['S (40×50 cm)', 'M (60×80 cm)', 'L (80×100 cm)', 'XL (100×120 cm)'],
    supplier: 'Ningbo, Çin — Doğrudan Üretici',
    supplierNote: 'CertiPUR-US sertifikalı köpük. Ücretsiz kargo. Aracısız, fabrikadan direkt.',
  },
  {
    id: 'cozynest-yuva',
    name: 'CozyNest Yuva Yatak',
    category: 'yatak',
    categoryLabel: 'Pelüş Yuva Yatak',
    price: 449,
    rating: 4.7,
    reviewCount: 224,
    badge: 'Yeni',
    images: [
      'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=700&h=520&fit=crop&auto=format&q=80',
      'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=700&h=520&fit=crop&auto=format&q=80',
    ],
    thumbImage: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&h=420&fit=crop&auto=format&q=80',
    shortDesc: 'Kapalı yuva tasarımı, ultra pelüş, ısı yalıtımlı.',
    description: 'CozyNest Yuva Yatak kedi ve küçük köpeklerin sevdiği kapalı yapısıyla güvenli ve sıcak bir uyku ortamı sunar. Çift yüz pelüş yaz-kış iki farklı konfor sağlar.',
    features: ['Kapalı yuva tasarımı', 'Ultra yumuşak çift yüz pelüş', 'Isı yalıtımlı iç yüzey', 'Çift taraflı kullanım (yaz/kış)', 'Çıkarılabilir yıkanabilir minder'],
    colors: ['Gri', 'Bej', 'Pembe', 'Kahverengi'],
    sizes: ['S (40 cm)', 'M (55 cm)', 'L (70 cm)'],
    supplier: 'Ningbo, Çin — Doğrudan Üretici',
    supplierNote: 'OEKO-TEX pelüş kumaş. Aracısız, fabrikadan direkt.',
  },
]

export function getProductById(id: string) {
  return PRODUCTS.find(p => p.id === id)
}
